name: Update Weather

on:
  workflow_dispatch:
  #pull_request:
  push:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-weather:
    name: Update weather module
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Run
        run: |
          gem install httparty
          
          ruby <<- EORUBY
            require 'httparty'
            
            README_FILE = './README.md'
            WEATHER_PLACEHOLDER_START = '<!-- WEATHER:BEGIN -->'
            WEATHER_PLACEHOLDER_END = '<!-- WEATHER:END -->'
            WEATHER_PLACEHOLDER_REGEX = /#{WEATHER_PLACEHOLDER_START}[\s\S]*?#{WEATHER_PLACEHOLDER_END}/

            weather = HTTParty.get('https://wttr.in/Allen,%20Texas,%20United%20States?TQ0', headers: { 'User-Agent': 'curl' }).body

            content = "\n\`\`\`\n#{weather}\`\`\`\n"

            readme = File.read(README_FILE)
            readme.gsub!(WEATHER_PLACEHOLDER_REGEX, "#{WEATHER_PLACEHOLDER_START}\n#{content}\n#{WEATHER_PLACEHOLDER_END}")

            File.open(README_FILE, 'w') { |f| f.puts readme }
          EORUBY
          
          git remote add github "https://github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only

          git add .

          git commit -m "Generated commit"
          git push github HEAD:${GITHUB_REF}
